CREATE TABLE br_checker_entrys (
 id int NOT NULL IDENTITY,
 TRACKER_TABLE_ID int not null,
 CALL_NO int default (0),
 CONSUMER_NAME varchar(1000) not null,
 CONSUMER_MOBILE_NUMBER varchar(18) not null,
 CALL_STATUS varchar(1000) default (''),
 CONTACTED tinyint,
 BAND tinyint,
 TIME_OF_CHECK varchar(100) default (''),
 DATE_AND_TIME date,
 AUDITOR_NAME varchar(1000) not null,
 AUDITOR_CODE varchar(100) not null,
 CLUSTER_NAME varchar(1000) not null,
 TSR_CODE varchar(100) not null,
 TSR_NAME varchar(1000) not null,
 TOTAL_VISITED int default (0),
 REMARK varchar(8000) not null,
 PICTURE_NAME varchar(1000) not null,
 PICTURE_URL varchar(1000),
 Latitude float,
 Longitude float,
 Accuracy float,
 PRIMARY KEY(id))